# Generated by Django 3.0 on 2022-03-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO profiles_profile (
                user_id,
                favorite_city
            )
            SELECT
                user_id,
                favorite_city
            FROM
                oc_lettings_site_profile;
            """)
    ]
