version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-test-lint-store:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"

      - run:
          name: Run tests
          command: |
            . env/bin/activate
            pytest --reuse-db

      - run:
          name: Run linting
          command: |
            . env/bin/activate
            flake8 --format=html --htmldir=flake-report

      - store_artifacts:
          path: flake-report/
          destination: flake-report

  containerization:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Containerize app and push to docker
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker build -t $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 .
            docker push $DOCKER_USER/oc-lettings:$CIRCLE_SHA1

  deployment:
    machine: true
    steps:
      - checkout
      - run:
          name: Push docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set secret_key=$secret_key -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set DEBUG=$DEBUG -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a $HEROKU_APP_NAME web

workflows:
  main:
    jobs:
      - build-test-lint-store
      - containerization:
          requires:
            - build-test-lint-store
          filters:
            branches:
              only: master
      - deployment:
          requires:
            - build-test-lint-store
            - containerization
          filters:
            branches:
              only: master

